clinic/api/urls.py
from django.urls import path
from clinic.api import views


urlpatterns = [
    path("testimonial/",views.TestimonialList.as_view(),name="testimonial-list"),
    path("testimonial/<int:pk>/", views.TestimonialRetrieve.as_view(), name="testimonial-retrieve"),
    path("doctor/",views.DoctorList.as_view(),name="doctor-list"),
    path("doctor/<int:pk>/", views.DoctorRetrieve.as_view(), name="doctor-retrieve"),
]

clinic/urls.py
from django.urls import path
from clinic import views

app_name = "clinic"
urlpatterns = [
    path("",views.index,name="home"),
    path("about/",views.about,name="about"),
    path("service/",views.service,name="service"),
    path("contact/",views.contact,name="contact"),
    path("pricing_plan/",views.pricing_plan,name="pricing_plan"),
    path("doctors/",views.dentist,name="doctors"),
    path("testimonial/",views.testimonial,name="testimonial"),
    path("appointment/",views.appointment,name="appointment"),
    path("appointment-page/",views.appointment_page,name="appointment_page"),
    path("doctors-search/",views.search,name="search"),
    path("contact_us/",views.contact_us,name="contact_us"),

]

django_cilinic_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from clinic import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index),
    path('clinic/', include('clinic.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clinic/models.py
from django.db import models


class Clinic(models.Model):

    name = models.CharField(max_length=255,default="")
    address = models.CharField(max_length=255,default="")
    email = models.EmailField(default="")
    number = models.CharField(max_length=255,default="")
    offer = models.CharField(max_length=255,blank=True)
    offer_desc = models.CharField(max_length=255,blank=True)
    instagram = models.CharField(max_length=255,blank=True)
    twitter = models.CharField(max_length=255,blank=True)
    facebook = models.CharField(max_length=255,blank=True)
    linkedin = models.CharField(max_length=255,blank=True)


    def __str__(self):
        return self.name


class About(models.Model):
    clinic = models.ForeignKey(Clinic,on_delete=models.CASCADE,related_name="about")
    maindesc = models.CharField(max_length=255,null=False,default="")
    firstdesc = models.CharField(max_length=255,null=True,blank=True)
    seconddesc = models.CharField(max_length=255, null=True, blank=True)
    image = models.ImageField(upload_to='images/about')


class Testimonial(models.Model):
    clinic = models.ForeignKey(Clinic,related_name="testimonial",on_delete=models.CASCADE)
    client_name = models.CharField(max_length=255)
    client_image = models.ImageField(upload_to='images/clients',default='./defaultClientPic.png')
    desc = models.CharField(max_length=600)

    def __str__(self):
        return  self.client_name



class OpeningTime(models.Model):
    clinic = models.ManyToManyField(Clinic,related_name="time_opening")
    time  = models.CharField(max_length=255)


class Doctor(models.Model):
    clinic = models.ManyToManyField(Clinic)
    name = models.CharField(max_length=255,default="")
    Expertise = models.CharField(max_length=255,default="")
    image =models.ImageField(upload_to='images/doctor',blank=True)
    instagram = models.CharField(max_length=255,blank=True)
    twitter = models.CharField(max_length=255,blank=True)
    facebook = models.CharField(max_length=255,blank=True)
    linkedin = models.CharField(max_length=255,blank=True)


    def __str__(self):
       return self.name


class Service(models.Model):
    doctor = models.ManyToManyField(Doctor,related_name="services")
    name = models.CharField(max_length=255,null=False)
    price = models.PositiveSmallIntegerField(null=False,default=0)
    desc = models.CharField(max_length=400,null=False)
    image = models.ImageField(upload_to="images/services",blank=True)

    def __str__(self):
        return self.name

clinic/api/views.py
from rest_framework import generics
from clinic.api import serializers as ser


class TestimonialList(generics.ListAPIView):
    serializer_class = ser.TestimonialSerializer


class TestimonialRetrieve(generics.RetrieveAPIView):
    serializer_class = ser.TestimonialSerializer


class DoctorList(generics.ListAPIView):
    serializer_class = ser.DoctorSerializer


class DoctorRetrieve(generics.RetrieveAPIView):
    serializer_class = ser.DoctorSerializer

clinic/views.py
from django.conf import settings
from django.shortcuts import render
from .models import Clinic , Doctor , Service , Testimonial
from django.views.decorators.http import require_POST
from django.core.mail import send_mail, get_connection
from django.contrib import messages
import re
# Create your views here.


def index(req):
    clinic = Clinic.objects.get(name="den_clinic")
    all_doctor = Doctor.objects.all()
    doctors = Doctor.objects.all()[:1]
    times = clinic.time_opening.all()
    services = Service.objects.all()
    about = clinic.about.get(clinic__name="den_clinic")
    testmonials = Testimonial.objects.all()
    index = True
    context = {
        "clinic" : clinic,
        "doctors" : doctors,
        "times" : times,
        "services" : services,
        "about" : about,
        "testimonials" : testmonials,
        "index" : index,
        "all_doctor" : all_doctor,

    }

    return render(req, 'clinic/index.html', context)


def about(req):
    clinic = Clinic.objects.get(name="den_clinic")
    about = Clinic.objects.get(name="den_clinic").about.get()
    about_active = True

    context = {
        "about":about,
        "clinic" : clinic,
        "about_active" : about_active
    }

    return render(req, 'clinic/about.html', context)


def service(req):

    clinic = Clinic.objects.get(name="den_clinic")
    services = Service.objects.all()
    service_active = True
    context = {
        "clinic" : clinic,
        "services" : services,
        "service_active" : service_active
    }

    return  render(req, "clinic/services.html",context=context)


def contact(req):
    clinic = Clinic.objects.get(name="den_clinic")
    contact_active = True
    context = {
        'clinic' : clinic,
        "contact_active" : contact_active
    }

    return  render(req,'clinic/contact.html',context)


def pricing_plan(req):
    clinic = Clinic.objects.get(name="den_clinic")
    services = Service.objects.all()

    context = {
        'clinic':clinic,
        'services' : services,
        'pages' : True,
        'pricing_plan_active' :True
    }

    return render(req,"clinic/pricing_plan.html",context)


def dentist(req):
    clinic = Clinic.objects.get(name="den_clinic")
    doctors = Doctor.objects.all()
    context = {
        "clinic":clinic,
        "doctors" : doctors,
        'pages' : True,
        'our_dentist_active' : True
    }
    return render(req,"clinic/dentist.html",context)

def testimonial(request):
    clinic = Clinic.objects.get(name="den_clinic")
    testmonials = Testimonial.objects.all()
    context = {
        "clinic" : clinic,
        "testmonials":testmonials,
        "pages" : True,
        'testimonial_active' : True
    }
    return render(request,"clinic/testimonial.html",context)


@require_POST
def appointment(request):

    service_id = request.POST['service_id']
    service_name = Service.objects.get(pk=service_id).name
    doctor_id = request.POST['doctor_id']
    doctor_name = Doctor.objects.get(pk=doctor_id).name
    name = request.POST['name']
    email = request.POST['email']
    date = request.POST['date']
    time = request.POST['time']
    regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b'

    clinic = Clinic.objects.get(name="den_clinic")
    context = {
        "clinic": clinic,

    }

    if re.fullmatch(regex, email):
        text = f"""
            name : {name}
            email : {email}
            service : {service_name}
            doctor  : {doctor_name}
            date  : {date}
            time : {time}
            
        """

        send_mail("appointment",text,"3inaroydl@gmail.com",("dentalapp109@gmail.com",))
        messages.success(request,"your message is send , we will call you soon")
        return render(request, 'clinic/email_sending.html', context)
    else:
        messages.error(request, "message doesn't send ")
        return render(request, 'clinic/email_sending.html', context)



def appointment_page(request):

    if request.method == "POST":
        appointment(request)
    elif request.method == "GET":
        clinic = Clinic.objects.get(name="den_clinic")
        context = {"clinic": clinic,
                   "doctors": Doctor.objects.all(),
                   "services" : Service.objects.all(),
                   "pages" : True,
                   "appointment_page_active" : True
                   }
        return render(request,'clinic/appointment.html',context)


def search(request):
    service_id = request.POST['service_id']
    service_name = Service.objects.get(pk=service_id)
    doctors = Doctor.objects.filter(services__name=service_name)
    clinic = Clinic.objects.get(name="den_clinic")
    context = {
        "clinic": clinic,
        "doctors": doctors
    }
    return render(request, "clinic/dentist.html", context)


def contact_us(request):
    name =request.POST['name']
    email = request.POST['email']
    subject = request.POST['subject']
    message = request.POST['message']
    clinic = Clinic.objects.get(name="den_clinic")
    context = {
        "clinic": clinic,

    }

    regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b'

    if re.fullmatch(regex, email):
        text = f"""
            name : {name}
            email : {email}
            message : {message}

        """

        send_mail(f"{subject}", text, "3inaroydl@gmail.com", ("dentalapp109@gmail.com",))
        messages.success(request, "your message is send , we will call you soon")
        return render(request, 'clinic/email_sending.html', context)
    else:
        messages.error(request, "message doesn't send ")
        return render(request, 'clinic/email_sending.html', context)

templates/clinic/about.html
{% extends 'base.html'  %}
{% load static %}


{% block body %}


     <!-- Full Screen Search Start -->
    <div class="modal fade" id="searchModal" tabindex="-1">
        <div class="modal-dialog modal-fullscreen">
            <div class="modal-content" style="background: rgba(9, 30, 62, .7);">
                <div class="modal-header border-0">
                    <button type="button" class="btn bg-white btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body d-flex align-items-center justify-content-center">
                    <div class="input-group" style="max-width: 600px;">
                        <input type="text" class="form-control bg-transparent border-primary p-3" placeholder="Type search keyword">
                        <button class="btn btn-primary px-4"><i class="bi bi-search"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Full Screen Search End -->


    <!-- Hero Start -->
    <div class="container-fluid bg-primary py-5 hero-header mb-5">
        <div class="row py-3">
            <div class="col-12 text-center">
                <h1 class="display-3 text-white animated zoomIn">About Us</h1>
                <a href="{% url 'clinic:home' %}" class="h4 text-white">Home</a>
                <i class="far fa-circle text-white px-2"></i>
                <a href="{% url 'clinic:about' %}" class="h4 text-white">About</a>
            </div>
        </div>
    </div>
    <!-- Hero End -->


    <!-- About Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-7">
                    <div class="section-title mb-4">
                        <h5 class="position-relative d-inline-block text-primary text-uppercase">About Us</h5>
                        <h1 class="display-5 mb-0">{{ about.maindesc }}</h1>
                    </div>
                    <h4 class="text-body fst-italic mb-4">{{ about.firstdesc }}</h4>
                    <p class="mb-4">{{ about.seconddesc }}</p>
                    <div class="row g-3">
                        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.3s">
                            <h5 class="mb-3"><i class="fa fa-check-circle text-primary me-3"></i>Award Winning</h5>
                            <h5 class="mb-3"><i class="fa fa-check-circle text-primary me-3"></i>Professional Staff</h5>
                        </div>
                        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.6s">
                            <h5 class="mb-3"><i class="fa fa-check-circle text-primary me-3"></i>24/7 Opened</h5>
                            <h5 class="mb-3"><i class="fa fa-check-circle text-primary me-3"></i>Fair Prices</h5>
                        </div>
                    </div>
                    <a href="appointment.html" class="btn btn-primary py-3 px-5 mt-4 wow zoomIn" data-wow-delay="0.6s">Make Appointment</a>

                </div>
                <div class="col-lg-5" style="min-height: 500px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute w-100 h-100 rounded wow zoomIn" data-wow-delay="0.9s" src="{{ about.image.url }}" style="object-fit: cover;">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->






{% endblock %}

templates/clinic/appointment.html
{% extends 'base.html' %}

{% block body %}
           <!-- Hero Start -->
    <div class="container-fluid bg-primary py-5 hero-header mb-5">
        <div class="row py-3">
            <div class="col-12 text-center">
                <h1 class="display-3 text-white animated zoomIn">Appointment</h1>
                <a href="{% url 'clinic:home' %}" class="h4 text-white">Home</a>
                <i class="far fa-circle text-white px-2"></i>
                <a href="{% url 'clinic:appointment_page' %}" class="h4 text-white">Appointment</a>
            </div>
        </div>
    </div>
    <!-- Hero End -->


         <!-- Appointment Start -->
    <div class="container-fluid bg-primary bg-appointment my-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div class="row gx-5">
                <div class="col-lg-6 py-5">
                    <div class="py-5">
                        <h1 class="display-5 text-white mb-4">We Are A Certified and Award Winning Dental Clinic You Can Trust</h1>
                        <p class="text-white mb-0">Eirmod sed tempor lorem ut dolores. Aliquyam sit sadipscing kasd ipsum. Dolor ea et dolore et at sea ea at dolor, justo ipsum duo rebum sea invidunt voluptua. Eos vero eos vero ea et dolore eirmod et. Dolores diam duo invidunt lorem. Elitr ut dolores magna sit. Sea dolore sanctus sed et. Takimata takimata sanctus sed.</p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="appointment-form h-100 d-flex flex-column justify-content-center text-center p-5 wow zoomIn" data-wow-delay="0.6s">
                        <h1 class="text-white mb-4">Make Appointment</h1>
                        <form action="{% url 'clinic:appointment' %}"  method="post">
                            {% csrf_token %}
                            <div class="row g-3">
                                <div class="col-12 col-sm-6">
                                    <select required class="form-select bg-light border-0" name="service_id" style="height: 55px;">
                                        {% for service in services %}
                                            <option value="{{ service.pk }}" >{{ service.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <select required class="form-select bg-light border-0" name="doctor_id" style="height: 55px;">
                                        {% for doctor in doctors %}
                                             <option value="{{ doctor.pk }}" >{{ doctor.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <input required type="text" class="form-control bg-light border-0" name="name" placeholder="Your Name" style="height: 55px;">
                                </div>
                                <div class="col-12 col-sm-6">
                                    <input required type="email" class="form-control bg-light border-0" name="email" placeholder="Your Email" style="height: 55px;">
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="date" id="date1" data-target-input="nearest">
                                        <input required type="text"
                                            class="form-control bg-light border-0 datetimepicker-input"
                                            placeholder="Appointment Date" data-target="#date1" data-toggle="datetimepicker" name="date" style="height: 55px;">
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="time" id="time1" data-target-input="nearest">
                                        <input required type="text"
                                            class="form-control bg-light border-0 datetimepicker-input"
                                            placeholder="Appointment Time" data-target="#time1" data-toggle="datetimepicker" name="time" style="height: 55px;">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button class="btn btn-dark w-100 py-3" type="submit">Make Appointment</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Appointment Start -->





{% endblock %}

templates/clinic/contact.html
{% extends 'base.html' %}




{% block body %}


    <!-- Hero Start -->
    <div class="container-fluid bg-primary py-5 hero-header mb-5">
        <div class="row py-3">
            <div class="col-12 text-center">
                <h1 class="display-3 text-white animated zoomIn">Contact Us</h1>
                <a href="{% url 'clinic:home' %}" class="h4 text-white">Home</a>
                <i class="far fa-circle text-white px-2"></i>
                <a href="{% url 'clinic:contact' %}" class="h4 text-white">Contact</a>
            </div>
        </div>
    </div>
    <!-- Hero End -->


    <!-- Contact Start -->
    <div class="container-fluid py-5">
        <div class="container">
            <div class="row g-5">
                <div class="col-xl-4 col-lg-6 wow slideInUp" data-wow-delay="0.1s">
                    <div class="bg-light rounded h-100 p-5">
                        <div class="section-title">
                            <h5 class="position-relative d-inline-block text-primary text-uppercase">Contact Us</h5>
                            <h1 class="display-6 mb-4">Feel Free To Contact Us</h1>
                        </div>
                        <div class="d-flex align-items-center mb-2">
                            <i class="bi bi-geo-alt fs-1 text-primary me-3"></i>
                            <div class="text-start">
                                <h5 class="mb-0">Our Office</h5>
                                <span>{{ clinic.address }}</span>
                            </div>
                        </div>
                        <div class="d-flex align-items-center mb-2">
                            <i class="bi bi-envelope-open fs-1 text-primary me-3"></i>
                            <div class="text-start">
                                <h5 class="mb-0">Email Us</h5>
                                <span>{{ clinic.email }}</span>
                            </div>
                        </div>
                        <div class="d-flex align-items-center">
                            <i class="bi bi-phone-vibrate fs-1 text-primary me-3"></i>
                            <div class="text-start">
                                <h5 class="mb-0">Call Us</h5>
                                <span>{{ clinic.number }}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-6 wow slideInUp" data-wow-delay="0.3s">
                    <form action="{% url 'clinic:contact_us' %}" method="post">
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-12">
                                <input required name="name" type="text" class="form-control border-0 bg-light px-4" placeholder="Your Name" style="height: 55px;">
                            </div>
                            <div class="col-12">
                                <input required  name="email" type="email" class="form-control border-0 bg-light px-4" placeholder="Your Email" style="height: 55px;">
                            </div>
                            <div class="col-12">
                                <input required name="subject" type="text" class="form-control border-0 bg-light px-4" placeholder="Subject" style="height: 55px;">
                            </div>
                            <div class="col-12">
                                <textarea required name="message" class="form-control border-0 bg-light px-4 py-3" rows="5" placeholder="Message"></textarea>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-primary w-100 py-3" type="submit">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-xl-4 col-lg-12 wow slideInUp" data-wow-delay="0.6s">
                    <iframe class="position-relative rounded w-100 h-100"
                        src="https://maps.google.com/maps?width=600&amp;height=400&amp;hl=en&amp;q=tehran&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"
                        frameborder="0" style="min-height: 400px; border:0;" allowfullscreen="" aria-hidden="false"
                        tabindex="0"></iframe>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->


{% endblock %}

templates/clinic/email_sending.html
{% extends 'base.html' %}

{% block body %}

    {% include 'includes/message.html' %}

{% endblock %}

templates/clinic/pricing_plan.html
{% extends 'base.html' %}





{% block body %}

        <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-5">
                    <div class="section-title mb-4">
                        <h5 class="position-relative d-inline-block text-primary text-uppercase">Pricing Plan</h5>
                        <h1 class="display-5 mb-0">We Offer Fair Prices for Dental Treatment</h1>
                    </div>
                    <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo eirmod magna dolore erat amet</p>
                    <h5 class="text-uppercase text-primary wow fadeInUp" data-wow-delay="0.3s">Call for Appointment</h5>
                    <h1 class="wow fadeInUp" data-wow-delay="0.6s">{{ clinic.number }}</h1>
                </div>
                <div class="col-lg-7">
                    <div class="owl-carousel price-carousel wow zoomIn" data-wow-delay="0.9s">
                        {% for service in services %}

                        <div class="price-item pb-4">
                            <div class="position-relative">
                                <img class="img-fluid rounded-top" src="{{ service.image.url }}" alt="">
                                <div class="d-flex align-items-center justify-content-center bg-light rounded pt-2 px-3 position-absolute top-100 start-50 translate-middle" style="z-index: 2;">
                                    <h2 class="text-primary m-0">${{ service.price }}</h2>
                                </div>
                            </div>
                            <div class="position-relative text-center bg-light border-bottom border-primary py-5 p-4">
                                <h4>{{ service.name }}</h4>
                                <hr class="text-primary w-50 mx-auto mt-0">
                                <div class="d-flex justify-content-between mb-3"><span>Modern Equipment</span><i class="fa fa-check text-primary pt-1"></i></div>
                                <div class="d-flex justify-content-between mb-3"><span>Professional Dentist</span><i class="fa fa-check text-primary pt-1"></i></div>
                                <div class="d-flex justify-content-between mb-2"><span>24/7 Call Support</span><i class="fa fa-check text-primary pt-1"></i></div>
                                <a href="{% url 'clinic:appointment_page' %}" class="btn btn-primary py-2 px-4 position-absolute top-100 start-50 translate-middle">Appointment</a>
                            </div>
                        </div>


                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Pricing End -->



{% endblock %}

templates/clinic/services.html
{% extends "base.html" %}
{% load static %}

{% block body %}

      <!-- Hero Start -->
    <div class="container-fluid bg-primary py-5 hero-header mb-5">
        <div class="row py-3">
            <div class="col-12 text-center">
                <h1 class="display-3 text-white animated zoomIn">Services</h1>
                <a href="{% url 'clinic:home' %}" class="h4 text-white">Home</a>
                <i class="far fa-circle text-white px-2"></i>
                <a href={% url 'clinic:service' %}"" class="h4 text-white">Services</a>
            </div>
        </div>
    </div>
    <!-- Hero End -->


    <!-- Service Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div class="row g-5 mb-5">
                <div class="col-lg-5 wow zoomIn" data-wow-delay="0.3s" style="min-height: 400px;">
                    <div class="twentytwenty-container position-relative h-100 rounded overflow-hidden">
                        <img class="position-absolute w-100 h-100" src="{% static 'cilinic/img/before.jpg' %}" style="object-fit: cover;">
                        <img class="position-absolute w-100 h-100" src="{% static 'cilinic/img/after.jpg' %}" style="object-fit: cover;">
                    </div>
                </div>
                <div class="col-lg-7">
                    <div class="section-title mb-5">
                        <h5 class="position-relative d-inline-block text-primary text-uppercase">Our Services</h5>
                        <h1 class="display-5 mb-0">We Offer The Best Quality Dental Services</h1>
                    </div>
                    <div class="row g-5">
                        {% for service in services %}
                            <div class="col-md-6 service-item wow zoomIn" data-wow-delay="0.6s">
                                <div class="rounded-top overflow-hidden">
                                    <img class="img-fluid" src="{{ service.image.url }}" alt="">
                                </div>
                                <div class="position-relative bg-light rounded-bottom text-center p-4">
                                    <h5 class="m-0">{{ service.name }}</h5>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="row g-5 wow fadeInUp" data-wow-delay="0.1s">
                <div class="col-lg-5 service-item wow zoomIn" data-wow-delay="0.9s">
                    <div class="position-relative bg-primary rounded h-100 d-flex flex-column align-items-center justify-content-center text-center p-4">
                        <h3 class="text-white mb-3">Make Appointment</h3>
                        <p class="text-white mb-3">Clita ipsum magna kasd rebum at ipsum amet dolor justo dolor est magna stet eirmod</p>
                        <h2 class="text-white mb-0">{{ clinic.number }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Service End -->







{% endblock %}

templates/clinic/testimonial.html
{% extends 'base.html' %}


{% block body %}

      <!-- Hero Start -->
    <div class="container-fluid bg-primary py-5 hero-header mb-5">
        <div class="row py-3">
            <div class="col-12 text-center">
                <h1 class="display-3 text-white animated zoomIn">Testimonial</h1>
                <a href="{% url 'clinic:home' %}" class="h4 text-white">Home</a>
                <i class="far fa-circle text-white px-2"></i>
                <a href="{% url 'clinic:testimonial' %}" class="h4 text-white">Testimonial</a>
            </div>
        </div>
    </div>
    <!-- Hero End -->


    <!-- Testimonial Start -->
    <div class="container-fluid bg-primary bg-testimonial py-5 mb-5 wow fadeInUp" data-wow-delay="0.1s" style="margin-top: 90px;">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    <div class="owl-carousel testimonial-carousel rounded p-5 wow zoomIn" data-wow-delay="0.6s">
                        {% for testmonial in testmonials %}

                            <div class="testimonial-item text-center text-white">
                            <img class="img-fluid mx-auto rounded mb-4" src="{{ testmonial.client_image.url }}" alt="">
                            <p class="fs-5">{{ testmonial.desc }}</p>
                            <hr class="mx-auto w-25">
                            <h4 class="text-white mb-0">{{ testmonial.client_name }}</h4>
                        </div>


                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Testimonial End -->





{% endblock %}