clinic/urls.py
from django.urls import path
from clinic import views

app_name = "clinic"
urlpatterns = [
    path("",views.index,name="home"),
    path("about/",views.about,name="about"),
    path("service/",views.service,name="service"),
    path("contact/",views.contact,name="contact"),
    path("pricing_plan/",views.pricing_plan,name="pricing_plan"),
    path("doctors/",views.dentist,name="doctors"),
    path("testimonial/",views.testimonial,name="testimonial"),
    path("appointment/",views.appointment,name="appointment"),
    path("appointment-page/",views.appointment_page,name="appointment_page"),
    path("doctors-search/",views.search,name="search"),
    path("contact_us/",views.contact_us,name="contact_us"),

]

django_cilinic_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from clinic import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index),
    path('clinic/', include('clinic.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{{ clinic.name }}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'cilinic/img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600;700&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'cilinic/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'cilinic/lib/animate/animate.min.css' %} " rel="stylesheet">
    <link href="{% static 'cilinic/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %} " rel="stylesheet" />
    <link href="{% static 'cilinic/lib/twentytwenty/jquery.twentytwenty.js' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'cilinic/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'cilinic/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-grow text-primary m-1" role="status">
            <span class="sr-only">Loading...</span>
        </div>
        <div class="spinner-grow text-dark m-1" role="status">
            <span class="sr-only">Loading...</span>
        </div>
        <div class="spinner-grow text-secondary m-1" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->


    <!-- Topbar Start -->
    <div class="container-fluid bg-light ps-5 pe-0 d-none d-lg-block">
        <div class="row gx-0">
            <div class="col-md-6 text-center text-lg-start mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center">
                </div>
            </div>
            <div class="col-md-6 text-center text-lg-end">
                <div class="position-relative d-inline-flex align-items-center bg-primary text-white top-shape px-5">
                    <div class="me-3 pe-3 border-end py-2">
                        <p class="m-0"><i class="fa fa-envelope-open me-2"></i>{{ clinic.email}}</p>
                    </div>
                    <div class="py-2">
                        <p class="m-0"><i class="fa fa-phone-alt me-2"></i>{{ clinic.number }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm px-5 py-3 py-lg-0">
        <a href="{% url 'clinic:home' %}" class="navbar-brand p-0">
            <h1 class="m-0 text-primary"><i class="fa fa-tooth me-2"></i>DentCare</h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
                <a href="{% url 'clinic:home' %}" class="nav-item nav-link {% if index %}active {% endif %} ">Home</a>
                <a href="{% url 'clinic:about' %}" class="nav-item nav-link {% if about_active %}active {% endif %} ">About</a>
                <a href="{% url 'clinic:service' %}" class="nav-item nav-link {% if service_active %} active {% endif %}">Service</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle {% if pages %} active {% endif %}  " data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu m-0">
                        <a href="{% url "clinic:pricing_plan" %}" class="dropdown-item{% if pricing_plan_active %}active {% endif %} ">Pricing Plan</a>
                        <a href="{% url 'clinic:doctors' %}" class="dropdown-item{% if our_dentist_active %} active {% endif %} ">Our Dentist</a>
                        <a href="{% url 'clinic:testimonial' %}" class="dropdown-item {% if testimonial_active %}active {% endif %} ">Testimonial</a>
                        <a href="{% url 'clinic:appointment_page' %}" class="dropdown-item {% if appointment_page_active %}active {% endif %}">Appointment</a>
                    </div>
                </div>
                <a href="{% url 'clinic:contact' %}" class="nav-item nav-link {% if contact_active %}active {% endif %} ">Contact</a>
            </div>
            <button type="button" class="btn text-dark" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fa fa-search"></i></button>
            <a href="{% url 'clinic:appointment_page' %}" class="btn btn-primary py-2 px-4 ms-3">Appointment</a>
        </div>
    </nav>
    <!-- Navbar End -->


    {% block body %}


    {% endblock %}






  <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light py-5 wow fadeInUp" data-wow-delay="0.3s" style="margin-top: -75px;">
        <div class="container pt-5">
            <div class="row g-5 pt-4">
                <div class="col-lg-3 col-md-6">
                    <h3 class="text-white mb-4">Quick Links</h3>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-light mb-2" href="{% url 'clinic:home' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                        <a class="text-light mb-2" href="{% url 'clinic:about' %}"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                        <a class="text-light mb-2" href="{% url 'clinic:service' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                        <a class="text-light" href="{% url 'clinic:contact' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h3 class="text-white mb-4">Popular Links</h3>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-light mb-2" href="{% url 'clinic:home' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                        <a class="text-light mb-2" href="{% url 'clinic:about' %}"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                        <a class="text-light mb-2" href="{% url 'clinic:service' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                        <a class="text-light" href="{% url 'clinic:contact' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h3 class="text-white mb-4">Get In Touch</h3>
                    <p class="mb-2"><i class="bi bi-geo-alt text-primary me-2"></i>{{ clinic.address }}</p>
                    <p class="mb-2"><i class="bi bi-envelope-open text-primary me-2"></i>{{ clinic.email }}</p>
                    <p class="mb-0"><i class="bi bi-telephone text-primary me-2"></i>{{ clinic.number }}</p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h3 class="text-white mb-4">Follow Us</h3>
                    <div class="d-flex">
                        <a class="btn btn-lg btn-primary btn-lg-square rounded me-2" href="{{ clinic.twitter }}"><i class="fab fa-twitter fw-normal"></i></a>
                        <a class="btn btn-lg btn-primary btn-lg-square rounded me-2" href="{{ clinic.facebook }}"><i class="fab fa-facebook-f fw-normal"></i></a>
                        <a class="btn btn-lg btn-primary btn-lg-square rounded me-2" href="{{ clinic.linkedin }}"><i class="fab fa-linkedin-in fw-normal"></i></a>
                        <a class="btn btn-lg btn-primary btn-lg-square rounded" href="{{ clinic.instagram }}"><i class="fab fa-instagram fw-normal"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid text-light py-4" style="background: #051225;">
        <div class="container">
            <div class="row g-0">
                <div class="col-md-6 text-center text-md-start">
                    <p class="mb-md-0">&copy; <a class="text-white border-bottom" href="#">Your Site Name</a>. All Rights Reserved.</p>
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <p class="mb-0">Designed by <a class="text-white border-bottom" href="https://htmlcodex.com">HTML Codex</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->



    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square rounded back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'cilinic/lib/wow/wow.min.js' %} "></script>
    <script src=" {% static 'cilinic/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'cilinic/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'cilinic/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'cilinic/lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'cilinic/lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'cilinic/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <script src="{% static 'cilinic/lib/twentytwenty/jquery.event.move.js ' %}"></script>
    <script src="{% static 'cilinic/lib/twentytwenty/jquery.twentytwenty.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'cilinic/js/main.js' %} "></script>
</body>

</html>